//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InDiet.Data.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InDietDBEntities : DbContext
    {
        public InDietDBEntities()
            : base("name=InDietDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Ailments> tbl_Ailments { get; set; }
        public virtual DbSet<tbl_CityMaster> tbl_CityMaster { get; set; }
        public virtual DbSet<tbl_RoleMaster> tbl_RoleMaster { get; set; }
        public virtual DbSet<tbl_TokenDetails> tbl_TokenDetails { get; set; }
        public virtual DbSet<tbl_UserAddress> tbl_UserAddress { get; set; }
        public virtual DbSet<tbl_UserAilments> tbl_UserAilments { get; set; }
        public virtual DbSet<tbl_UserMaster> tbl_UserMaster { get; set; }
        public virtual DbSet<tbl_UserMasterGraphics> tbl_UserMasterGraphics { get; set; }
        public virtual DbSet<tbl_UserRoleMapping> tbl_UserRoleMapping { get; set; }
    }
}
