//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InDiet.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TokenDetails
    {
        public long ID { get; set; }
        public string MobileNumber { get; set; }
        public string Token { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
